# Site settings
title       : Because it matters
description : Making things happen, making things right, because it matters.
author      : Alan Tai
baseurl     : https://alantai.dev

# Page settings
markdown      : kramdown
highlighter   : rouge
paginate      : 5
paginate_path : page/:num

remote_theme : ayltai/kiss

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jemoji
